### ISSUE TITLE
Ancestors / Descendants list updated inproperly

### ISSUE THREAD

**Issue by migajek** [BrandyFx/Grapes#2]
Today I've started working with BrandyGrapes, and found out that the Ancestors / Descendants collections were not updated properly.
After some debugging I found out that the value of public property is different from the private field.

As you can see on the screenshot, the "descendants" field contains 0 elements while the Descendants property contains 4 of them (of course, the latter one is proper)
![image](https://cloud.githubusercontent.com/assets/581492/7183872/41ee9600-e45a-11e4-9341-d4cd93251455.png)

I've fixed it by changing all the references in the source code from fields to properties, now it works fine.
I'm curious what might be the reason. 
I haven't changed the mappings (Using Fluent)

NHibernate 4.0.3.4  + Fluent 2.0.1

**Comment by hazzik** [comment]
Do you use mapping helpers provided? The helpers suppose to map to fields. 

The `UpdateAncestorsDescendatRelation` uses fields to avoid unnecessary initialization, as I recall.

**Comment by migajek** [comment]
Do you mean the extension class for FluentNH which configures the mappings
of the TreeEntry fields?  Yeah I do use that, so the mappings are
configured with AccessStrategy CamelCaseField. When Ive deleted the fields,
NH threw an exception.
BTW the properties are just getters which return underlying field value.
This is convenient for me as they're not implementing setters so I don't
have to explicitly ignore them in AutoMapper config (read-only props are
excluded automatically)
16 kwi 2015 23:23 "Alexander Zaytsev" <notifications@github.com> napisał(a):

**Comment by hazzik** [comment]
Ok, I'll try to take a look over the weekend.

**Comment by hazzik** [comment]
@migajek. I've tried to make a test which would fail, but I can not. Can you please make one? 

Btw, the private field and Property have different values because of debugger.

**Comment by migajek** [comment]
Hi, I've found out that the problem only occurs when I use "Load" method to load the (proxy) of parent before saving the new entity. Switching to Get instead of Load works fine. 
The source code of bug demo is below, have a look at the BugDemo.Run method.

Uncomment the define in the first line of file to use "custom" version of Grapes which uses Properties instead of fields

oh and btw I had to use 2-parameter MapTree method as ``typeof(T) + string`` evaluates to type's full name:
```
typeof(T) + "a"
"BrandyGrapesBugDemo.Categorya"
``` which is incorrect because of the dot (at least causes problems on SQLite)

```
//#define USE_CUSTOM_GRAPES

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FluentNHibernate.Cfg;
using FluentNHibernate.Cfg.Db;
using FluentNHibernate.Mapping;
using NHibernate;
using NHibernate.Tool.hbm2ddl;



namespace BrandyGrapesBugDemo
{

    public class Category : 
#if USE_CUSTOM_GRAPES
        BrandyGrapesBugDemo.TreeEntry<Category>
#else 
        Brandy.Grapes.TreeEntry<Category>
#endif
    {        
        public virtual string Name { get; set; }        
    }

    public class CategoryMap : ClassMap<Category>
    {
        public CategoryMap()
        {            
            Id(x => x.Name);            
#if USE_CUSTOM_GRAPES
            BrandyGrapesBugDemo.TreeEntryMap.MapTree(this, "CategoryHierarchy");
#else
            Brandy.Grapes.FluentNHibernate.TreeEntryMap.MapTree(this, "CategoryHierarchy");            
#endif
        }
    }
    
    public class BugDemo
    {
        private readonly ISessionFactory sessionFactory;

        public BugDemo()
        {
            if (File.Exists("demo.db"))
                File.Delete("demo.db");
            sessionFactory =
                Fluently.Configure()
                    .Database(SQLiteConfiguration.Standard.UsingFile("demo.db"))
                    .Mappings(m => m.FluentMappings.AddFromAssemblyOf<CategoryMap>())
                    .ExposeConfiguration(cfg => new SchemaUpdate(cfg).Execute(false, true))
                    .BuildSessionFactory();
        }

        public void Run()
        {
            // create root and level 1 child
            using (var session = sessionFactory.OpenSession())
            using (var tx = session.BeginTransaction())
            {
                var root = new Category() {Name = "root"};
                session.Save(root);
                session.Save(new Category()
                {
                    Name = "1. Child",
                    Parent = root,                    
                });
                tx.Commit();
            }

            // create level 2 child
            using (var session = sessionFactory.OpenSession())
            using (var tx = session.BeginTransaction())
            {
                var parent = session.Load<Category>("1. Child");
                //var parent = session.Get<Category>("1. Child"); // switching to Get solves the problem
                session.Save(new Category()
                {
                    Name = "1.1. Child",
                    Parent = parent,                    
                });
                tx.Commit();
            }

            // root now should have 2 descendants
            using (var session = sessionFactory.OpenSession())
            {
                var root = session.Get<Category>("root");
                Console.WriteLine(root.Descendants.Count());
            }
        }
    }
   
    public abstract class TreeEntry<T>
       where T : TreeEntry<T>
    {
        protected bool UpdateHierarchy;
        readonly ISet<T> ancestors = new HashSet<T>();
        readonly ISet<T> children = new HashSet<T>();
        readonly ISet<T> descendants = new HashSet<T>();
        T parent;

        protected TreeEntry()
            : this(true)
        {
        }

        protected TreeEntry(bool updateHierarchy)
        {
            UpdateHierarchy = updateHierarchy;
        }

        public virtual T Parent
        {
            get { return parent; }
            set
            {
                if (UpdateHierarchy && parent != null)
                {
                    var collection = parent.Children;
                    collection.Remove(This);
                    UpdateAncestorDescendantRelation(parent, This, false);
                }
                parent = value;
                if (UpdateHierarchy && parent != null)
                {
                    var collection = parent.Children;
                    collection.Add(This);
                    UpdateAncestorDescendantRelation(parent, This, true);
                }
            }
        }

        public virtual ISet<T> Children
        {
            get { return children; }
        }

        public virtual ISet<T> Ancestors
        {
            get { return ancestors; }
        }

        public virtual ISet<T> Descendants
        {
            get { return descendants; }
        }

        protected T This
        {
            get { return (T)this; }
        }

        public virtual void AddChild(T child)
        {
            if (child == null) throw new ArgumentNullException("child");
            child.Parent = This;
        }

        public virtual void RemoveChild(T child)
        {
            if (child == null) throw new ArgumentNullException("child");
            child.Parent = null;
        }

        static void UpdateAncestorDescendantRelation(T ancestor, T descendant, bool addRelation)
        {
            if (ancestor.Parent != null)
                UpdateAncestorDescendantRelation(ancestor.Parent, descendant, addRelation);
            foreach (var grandDescendant in descendant.Children)
                UpdateAncestorDescendantRelation(ancestor, grandDescendant, addRelation);
            var ancestorDescendants = ancestor.Descendants;
            var descendantAncestors = descendant.Ancestors;
            if (addRelation)
            {
                ancestorDescendants.Add(descendant);
                descendantAncestors.Add(ancestor);
            }
            else
            {
                ancestorDescendants.Remove(descendant);
                descendantAncestors.Remove(ancestor);
            }
        }
    }

    public static class TreeEntryMap
    {
        public static void MapTree<T>(this ClasslikeMapBase<T> map)
            where T : TreeEntry<T>
        {
            MapTree(map, typeof(T) + "_HIERARCHY");
        }

        public static void MapTree<T>(this ClasslikeMapBase<T> map, string hierarchyTableName)
            where T : TreeEntry<T>
        {
            map.References(x => x.Parent)
                .Access.CamelCaseField()
                .Nullable()
                .Column("PARENT_ID");

            map.HasMany(x => x.Children)
                .Access.CamelCaseField()
                .Cascade.All()
                .Inverse()
                .AsSet()
                .LazyLoad()
                .BatchSize(250)
                .KeyColumn("PARENT_ID");

            map.HasManyToMany(x => x.Ancestors)
                .Access.CamelCaseField()
                .Cascade.None()
                .AsSet()
                .LazyLoad()
                .BatchSize(250)
                .Table(hierarchyTableName)
                .ParentKeyColumn("CHILD_ID")
                .ChildKeyColumn("PARENT_ID")
                .ForeignKeyConstraintNames(string.Format("FK_{0}_CHILD", hierarchyTableName), null);

            map.HasManyToMany(x => x.Descendants)
                .Access.CamelCaseField()
                .Cascade.All()
                .Inverse()
                .AsSet()
                .LazyLoad()
                .BatchSize(250)
                .Table(hierarchyTableName)
                .ParentKeyColumn("PARENT_ID")
                .ChildKeyColumn("CHILD_ID")
                .ForeignKeyConstraintNames(string.Format("FK_{0}_PARENT", hierarchyTableName), null);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            new BugDemo().Run();
            Console.ReadLine();
        }
    }
}
```

**Comment by hazzik** [comment]
@migajek can you check [Brandy.Grapes v1.0.5](https://www.nuget.org/packages/Brandy.Grapes/1.0.5)?

**Comment by migajek** [comment]
seems to be working fine. thanks.
